name: poodle
root: ~/workbench/hound/cmd/poodle

windows:
  - EDITOR: nvim .
  - TEST:
  - CONSOLE: node
  - NOTES: cd ~/notes/  && vim $(date -v -Mon "+%Y-%m-%d")-notes.md
  - TILT/HOUND:
    layout: even-horizontal
    panes:
      - tilt cd ~/workbench/hound/
      - cd ~/workbench/hound/
  - TODO: note todo
