name: poodle
root: ~/workbench/hound/cmd/poodle

windows:
  - EDITOR: nvim .
  - TEST:
  - CONSOLE:
      layout: even-horizontal
      panes:
        - node:
        - etc:
  - NOTES: cd ~/notes/  && vim $(date -v -Mon "+%Y-%m-%d")-notes.md
  - TILT/HOUND:
      layout: even-horizontal
      root: ~/workbench/hound/
      panes:
        - tilt:
        - hound:
  - TODO: todo
